"""Initial migration.

Revision ID: 7b46cbfef48b
Revises: 
Create Date: 2021-05-14 16:01:14.716350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b46cbfef48b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Guest',
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=30), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('license_plate', sa.String(length=30), nullable=True),
    sa.Column('consent_expire_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('guest_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('license_plate'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('socket_user_manager',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('Appointment',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('checked_in', sa.DateTime(), nullable=True),
    sa.Column('checked_out', sa.DateTime(), nullable=True),
    sa.Column('has_pass', sa.Boolean(), nullable=True),
    sa.Column('employee_name', sa.String(length=50), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['Guest.guest_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Appointment')
    op.drop_table('socket_user_manager')
    op.drop_table('User')
    op.drop_table('Guest')
    # ### end Alembic commands ###
