"""empty message

Revision ID: 88c4c3daee0c
Revises: f92ff407ccbc
Create Date: 2021-06-11 16:51:41.686467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88c4c3daee0c'
down_revision = 'f92ff407ccbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_table('socket_user_manager')
    op.drop_table('Appointment')
    op.drop_index('email', table_name='User')
    op.drop_table('User')
    op.drop_table('Guest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Guest',
    sa.Column('guest_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('company', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('license_plate', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('consent_expire_date', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('guest_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('User',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`is_admin` in (0,1))', name='User_chk_1'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'User', ['email'], unique=True)
    op.create_table('Appointment',
    sa.Column('appointment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('checked_in', mysql.DATETIME(), nullable=True),
    sa.Column('checked_out', mysql.DATETIME(), nullable=True),
    sa.Column('has_pass', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('employee_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('guest_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`has_pass` in (0,1))', name='Appointment_chk_1'),
    sa.ForeignKeyConstraint(['guest_id'], ['Guest.guest_id'], name='Appointment_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('socket_user_manager',
    sa.Column('_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
