"""test

Revision ID: dd915704dd71
Revises: 
Create Date: 2021-03-17 09:35:00.351476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd915704dd71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Guest',
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=30), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('license_plate', sa.String(length=30), nullable=True),
    sa.Column('consent_duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('guest_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('license_plate'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('Appointment',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('checked_in', sa.DateTime(), nullable=True),
    sa.Column('checked_out', sa.DateTime(), nullable=True),
    sa.Column('pass_id', sa.Integer(), nullable=True),
    sa.Column('employee_name', sa.String(length=50), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['Guest.guest_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('Image',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['Guest.guest_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Image')
    op.drop_table('Appointment')
    op.drop_table('User')
    op.drop_table('Guest')
    # ### end Alembic commands ###
